### ISSUE TITLE
Building Server on Local Ubuntu

### ISSUE THREAD

**Issue by KalimdorTheKing** [dmsl/anyplace#132] opened 2017-05-23 13:40 UTC
Hi,
We are planning to build anyplace server on a local ubuntu linux computer. However, due to the old components being needed, we faced many problems during installation. We started compiling for Ubuntu 12.04.  We had a problem following the compilation guide for Couchbase 2.1.1. We installed Couchbase 3.1 directly afterwards and then installed the views.  We could restore it by deleting the rows section in the View file. 

Afterwards, while running PlayFramework 2.2.6, problems still existed in the scala, sbt and activator versions. We are experiencing dependency problems.

Could you tell us the necessary linux operating system and component versions so that we can create this compilation environment without problems?

If you have a more detailed document to create this environment, can you help me find it?

Thanks in advance for your support.

**Comment by ameleito** [comment] 2017-05-25 14:16
Hi Kalimdor.

I started yesterday with instalation of server, but i dont get the solution yet, its the same issue with dependencies, i wanna know could you check something about instalation, or we are at same stpe until now.

regards and again thanks for help.

**Comment by KalimdorTheKing** [comment] 2017-05-25 14:47
Hi ameleito,
I could build source codes yesterday finally. But it was more troublesome than I expected. I have found some dependent jar files (like scala-library 2-10-2, sbt, scala etc.) manually from the internet. At the and I have run AnyPlaceServer or I think it is. Now I will continue to work on it quite a bit.

I did not have a problem cloning the server codes.

**Comment by ameleito** [comment] 2017-05-25 15:40
Hi Kalimdor

well i cloned the source, but when i use sbt from console i receive some errors about dependencies like:

        at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: download failed: com.typesafe.play#sbt-
plugin;2.2.1!sbt-plugin.jar
[error] download failed: com.typesafe.play#routes-compiler_2.10;2.2.1!routes-com
piler_2.10.jar
[error] download failed: com.typesafe.play#templates-compiler_2.10;2.2.1!templat
es-compiler_2.10.jar
[error] download failed: com.typesafe.sbteclipse#sbteclipse-core;2.4.0!sbteclips
e-core.jar
[error] download failed: com.typesafe.sbt#sbt-native-packager;0.6.2!sbt-native-p
ackager.jar
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

then that is the problem, i donwload the files sbt and scala-ide, but actually i don't know how to continue with this, cause i'm Java on Eclipse, and i never worked that way with scala and all of that, then i feel some lost, do you have some advise or how can start the server or not.

Regards and thanks for your help

**Comment by ameleito** [comment] 2017-05-25 21:01
Hi KalimdorTheKing

Finally i can load the server compile and everything, the issue now its a little problem with the database, cause i'm receiving the follow messages:

IllegalArgumentException: Illegal character in scheme name at index 0: IP:Port/pools 

i dont know exactly wich is the IP and Port that i have to pass, cause i send the IP and port of machine where the database is installed. but i receive that messages.

Well any advice will be welcome.

Regards
Leonardo Amezquita

**Comment by ameleito** [comment] 2017-05-26 15:08
hi again

I wanna share with you my little advance, yesterday i compiled and run the server finally, after that i try to add the building and i saw the request arriving to couchbase, but then i cant saw that in arquitect, do you know if i have to rebuild the project architect cause i change a lot of files where you can see the server of creators then i need it to change to the new server but again the control dont get the buildings actually i dont know how to follow do you have some advises. 

Regards
Leonardo Amezquita

**Comment by mzglinski** [comment] 2017-06-12 21:01
Hi,
@ameleito did you manage to run server with couchbase 3.x? If yes, how did you do it, right now I am receiving error 401 (forbidden) while trying to connect to the database. Right after first request about pools.

Any hints would be much appreciated.
Thanks in advance.

**Comment by ameleito** [comment] 2017-06-12 21:43
Hi  @mzglinski i tried that but i get errors, i didnt find the resource to load the schema on couchbase, and now that is the issue, that we need the schemas, and i don't know where find them for 3.x. do you install couchbase without problem, and you can get inside of console?

**Comment by mzglinski** [comment] 2017-06-12 21:52
Hi, yes I did. I've installed couchbase 3.x on debian jessie, then I imported views into couchbase using cbrestore, but first you have to remove "rows" from ddocs.json (leave only array in json file) and place the file in eg. import/bucket-default/design.json. Now you will be able to import docs&views into couchbase (import bucket name id default and path is import), but after that when i try to start the server i get error 401, despite the fact that with simple curl I'am able to download necessary data from /pools endpoint, so my guess is that 3.x version might be to different from 2.x.

**Comment by ameleito** [comment] 2017-06-13 01:42
Hi again, here is the question, can you put the config, you change that on
server, cause you need change everything about the connections on server, i
will say that the issue is dont find server cause you need change the
configs about it.

actually i resolve the connection, but the error for me its about the
structure, let me check tomorrow, and i'll send you the string of
conection, and if you can help me with the structure that will be great.

Regards.

2017-06-12 16:52 GMT-05:00 mzglinski <notifications@github.com>:

**Comment by anyplaceucy** [comment] 2017-08-02 10:55
Fixed in Anyplace v3. For more check the github page: https://github.com/dmsl/anyplace

**Closed by anyplaceucy** 2017-08-02 10:55 UTC
